purchase_type: on_demand
subnet_id: subnet-foobar
num_instances: 4
key_name: foobar-keypair
security_group_ids: sg-foobar
instance_type: m5.large
tag_name: kafka-cluster
vol_size: 120
role: worker
use_eips: true
