purchase_type: on_demand
subnet_id: subnet-0e0bee47eb78a732b
num_instances: 4
key_name: david-IAM-keypair
security_group_ids: sg-0fbc0d9385fd46dc0
instance_type: m5.large
tag_name: kafka-cluster
vol_size: 120
role: worker
use_eips: true
