purchase_type: on_demand
subnet_id: subnet-0c26e408f5494c8c9
num_instances: 2
key_name: david-IAM-keypair
security_group_ids: sg-06b9b1eee1ab9920d
instance_type: t3a.medium
tag_name: zookeeper-cluster
vol_size: 15
role: worker
use_eips: true
